language: python

python:
    - "3.9"

install:
    - pip install -e . -r ./requirements/dev

script:
    - nosetests runfolder_tests/unit
    - ./runfolder_tests/run_integration_tests.py

notifications:
    email: false
